# Generated by Django 4.1 on 2023-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_username",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
