# Generated by Django 4.1 on 2023-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_post_post_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
